version: 2.1

jobs:
  build_nightly:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    steps:
      - run:
          name: Getting LLVM18
          command: |
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 18
      - run: 
          name: Build
          command: cargo build --release
      - run:
          name: Run tests
          command: cargo test --release

workflows:
  openvaf_workflow:
    jobs:
      - build_nightly
