version: 2.1

jobs:
  build-nightly:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    steps:
      - run:
        name: Getting LLVM18
        command: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 18
      #- run:
      #  name: Getting rust
      #  command: 
      - run: 
        name: Build
        command: cargo build --release
      - run:
        name: Run tests
        command: cargo test --release

workflows:
  jobs:
    - build-nightly
